version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: db_ecommerce
    ports:
      - "5433:5432"
    networks:
      - ecommerce_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  ecommerce_network:
    driver: bridge
