spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5433/db_ecommerce
    username: admin
    password: 12345678
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: dev

  jwt:
    token:
      secret-key: vinicius_lemes  # Chave secreta para assinar os tokens
      expire-length: 3600000  # Tempo de expiração do Access Token (em milissegundos)
    refresh-token:
      expire-length: 86400000  # Tempo de expiração do Refresh Token (em milissegundos)

  security:
    encoder:
      id: pbkdf2
      secret: vinicius
      iterations: 185000
      hash-width: 256

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

aws:
  region: us-east-1
  bucket:
    name: ecommerce-lemes-project
